MODEL:
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [1.0, 1.0, 1.0]  # Since pre-trained weights use 1/1/1/
  DAFNE:
    CENTERNESS_ALPHA: 5
    LOSS_LAMBDA:
      CLS: 10.0
      CORNERS: 1.0
      CTR: 1.0

  # This always downloads the weights anew
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"

DATASETS:
  TRAIN: ("dota_1_5_train_600",)
  TEST: ("dota_1_5_val_600",)

DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.2
  ASPECT_RATIO_GROUPING: False

SOLVER:
  REFERENCE_WORLD_SIZE: 4
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000

INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 600
  MAX_SIZE_TEST: 600
  MIN_SIZE_TEST: 600
  ROTATION_AUG_ANGLES: [0.0, 90.0, 180.0, 270.0]
  RESIZE_TYPE: "shortest-edge"

TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 2000

  AUG:
    ENABLED: False
    MIN_SIZES: (150, 300, 450, 600, 900)
    MAX_SIZE: 900
    FLIP: True

VERSION: 2
