MODEL:
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [1.0, 1.0, 1.0]
  DAFNE:
    NUM_CLASSES: 1
    LOSS_LAMBDA:
      CLS: 1.0
      CORNERS: 1.0
      CENTER: 1.0
      CTR: 1.0

    ENABLE_LEVEL_SIZE_FILTERING: False

  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"



DATASETS:
  TRAIN: ("hrsc_trainval",)
  TEST: ("hrsc_test",)

SOLVER:
  REFERENCE_WORLD_SIZE: 4
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000

INPUT:
  RESIZE_TYPE: "shortest-edge"
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1200

  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1200

TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 2000

  AUG:
    ENABLED: False
    MIN_SIZES: (150, 200, 400, 600, 800, 1200)
    MAX_SIZE: 1200
    FLIP: True

VERSION: 2
