MODEL:
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [1.0, 1.0, 1.0]
  DAFNE:
    NUM_CLASSES: 1
    CENTERNESS_ALPHA: 5
    LOSS_LAMBDA:
      CLS: 10.0
      CORNERS: 1.0
      CENTER: 1.0
      CTR: 1.0

  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"

DATASETS:
  TRAIN: ("icdar15_train","icdar15_val")
  TEST: ("icdar15_test",)

DATALOADER:
  # SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  # REPEAT_THRESHOLD: 0.2
  ASPECT_RATIO_GROUPING: False

SOLVER:
  REFERENCE_WORLD_SIZE: 4
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (80000, 100000)
  MAX_ITER: 120000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 2000

INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1200
  MAX_SIZE_TEST: 1200
  MIN_SIZE_TEST: 1200
  RESIZE_TYPE: "shortest-edge"

TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 2000

  AUG:
    ENABLED: True
    MIN_SIZES: [450, 500, 600, 700, 800, 900, 1000, 1100, 1280]
    MAX_SIZE: 1280
    FLIP: True

VERSION: 2
